export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE',
    
    GET_USER: 'GET_USER',
};


export const jobConstant = {
    CREATE_JOB: 'CRATE_JOB',
    GET_JOB: 'GET_JOB',
    GET_JOB_WORKERS: 'GET_JOB_WORKERS',
    GET_ALL_JOBS_FOR_WORKERS: 'GET_ALL_JOBS_FOR_WORKERS',
    APPLY_FOR_JOB: 'APPLY_FOR_JOB',
    UPDATE_JOB_APPLICATION_STATUS: 'UPDATE_JOB_APPLICATION_STATUS',
    GET_EMPLOYER_JOBS: 'GET_EMPLOYER_JOBS'
}